import '../../enum/electric_charge_units.dart';
import '../../enum/prefix.dart';
import '../others/prefix_value.dart';

// Conversion factors to baseUnit
final Map<ElectricChargeUnits, double> electricChargeConversionDetails = {
  // Base unit
  ElectricChargeUnits.coulomb: 1,

  ElectricChargeUnits.abCoulomb: 10,
  ElectricChargeUnits.ampereHour: 3600,
  ElectricChargeUnits.ampereSecond: 1,
  ElectricChargeUnits.attoAmpereHour: 3600 * prefixValue[Prefix.atto],
  ElectricChargeUnits.attoAmpereSecond: prefixValue[Prefix.atto],
  ElectricChargeUnits.attoCoulomb: prefixValue[Prefix.atto],
  ElectricChargeUnits.centiAmpereHour: 3600 * prefixValue[Prefix.centi],
  ElectricChargeUnits.centiAmpereSecond: prefixValue[Prefix.centi],
  ElectricChargeUnits.centiCoulomb: prefixValue[Prefix.centi],
  ElectricChargeUnits.decaAmpereHour: 3600 * prefixValue[Prefix.deca],
  ElectricChargeUnits.decaAmpereSecond: prefixValue[Prefix.deca],
  ElectricChargeUnits.decaAmpereHour: prefixValue[Prefix.deca],
  ElectricChargeUnits.deciAmpereHour: 3600 * prefixValue[Prefix.deci],
  ElectricChargeUnits.deciAmpereSecond: prefixValue[Prefix.deci],
  ElectricChargeUnits.deciCoulomb: prefixValue[Prefix.deci],
  ElectricChargeUnits.exaAmpereHour: 3600 * prefixValue[Prefix.exa],
  ElectricChargeUnits.exaAmpereSecond: prefixValue[Prefix.exa],
  ElectricChargeUnits.exaCoulomb: prefixValue[Prefix.exa],
  ElectricChargeUnits.femtoAmpereHour: 3600 * prefixValue[Prefix.femto],
  ElectricChargeUnits.femtoAmpereSecond: prefixValue[Prefix.femto],
  ElectricChargeUnits.femtoCoulomb: prefixValue[Prefix.femto],
  ElectricChargeUnits.gigaAmpereHour: 3600 * prefixValue[Prefix.giga],
  ElectricChargeUnits.gigaAmpereSecond: prefixValue[Prefix.giga],
  ElectricChargeUnits.gigaCoulomb: prefixValue[Prefix.giga],
  ElectricChargeUnits.hectoAmpereHour: 3600 * prefixValue[Prefix.hecto],
  ElectricChargeUnits.hectoAmpereSecond: prefixValue[Prefix.hecto],
  ElectricChargeUnits.hectoCoulomb: prefixValue[Prefix.hecto],
  ElectricChargeUnits.kiloAmpereHour: 3600 * prefixValue[Prefix.kilo],
  ElectricChargeUnits.kiloAmpereSecond: prefixValue[Prefix.kilo],
  ElectricChargeUnits.kiloCoulomb: prefixValue[Prefix.kilo],
  ElectricChargeUnits.megaAmpereHour: 3600 * prefixValue[Prefix.mega],
  ElectricChargeUnits.megaAmpereSecond: prefixValue[Prefix.mega],
  ElectricChargeUnits.megaCoulomb: prefixValue[Prefix.mega],
  ElectricChargeUnits.microAmpereHour: 3600 * prefixValue[Prefix.micro],
  ElectricChargeUnits.microAmpereSecond: prefixValue[Prefix.micro],
  ElectricChargeUnits.microCoulomb: prefixValue[Prefix.micro],
  ElectricChargeUnits.milliAmpereHour: 3600 * prefixValue[Prefix.milli],
  ElectricChargeUnits.milliAmpereSecond: prefixValue[Prefix.milli],
  ElectricChargeUnits.milliCoulomb: prefixValue[Prefix.milli],
  ElectricChargeUnits.nanoAmpereHour: 3600 * prefixValue[Prefix.nano],
  ElectricChargeUnits.nanoAmpereSecond: prefixValue[Prefix.nano],
  ElectricChargeUnits.nanoCoulomb: prefixValue[Prefix.nano],
  ElectricChargeUnits.petaAmpereHour: 3600 * prefixValue[Prefix.peta],
  ElectricChargeUnits.petaAmpereSecond: prefixValue[Prefix.peta],
  ElectricChargeUnits.petaCoulomb: prefixValue[Prefix.peta],
  ElectricChargeUnits.picoAmpereHour: 3600 * prefixValue[Prefix.pico],
  ElectricChargeUnits.picoAmpereSecond: prefixValue[Prefix.pico],
  ElectricChargeUnits.picoCoulomb: prefixValue[Prefix.pico],
  ElectricChargeUnits.teraAmpereHour: 3600 * prefixValue[Prefix.tera],
  ElectricChargeUnits.teraAmpereSecond: prefixValue[Prefix.tera],
  ElectricChargeUnits.teraCoulomb: prefixValue[Prefix.tera],
  ElectricChargeUnits.yoctoAmpereHour: 3600 * prefixValue[Prefix.yocto],
  ElectricChargeUnits.yoctoAmpereSecond: prefixValue[Prefix.yocto],
  ElectricChargeUnits.yoctoCoulomb: prefixValue[Prefix.yocto],
  ElectricChargeUnits.yottaAmpereHour: 3600 * prefixValue[Prefix.yotta],
  ElectricChargeUnits.yottaAmpereSecond: prefixValue[Prefix.yotta],
  ElectricChargeUnits.yottaCoulomb: prefixValue[Prefix.yotta],
  ElectricChargeUnits.zeptoAmpereHour: 3600 * prefixValue[Prefix.zepto],
  ElectricChargeUnits.zeptoAmpereSecond: prefixValue[Prefix.zepto],
  ElectricChargeUnits.zeptoCoulomb: prefixValue[Prefix.zepto],
  ElectricChargeUnits.zettaAmpereHour: 3600 * prefixValue[Prefix.zetta],
  ElectricChargeUnits.zettaAmpereSecond: prefixValue[Prefix.zetta],
  ElectricChargeUnits.zettaCoulomb: prefixValue[Prefix.zetta],
};
