/// Supported conversion types
enum ConversionType {
  acceleration,
  area,
  bloodCholesterol,
  bloodGlucose,
  capacitance,
  data,
  dynamicViscocity,
  electricCharge,
  electricConductance,
  electricCurrent,
  electricPotential,
  electricResistance,
  force,
  frequency,
  illuminance,
  inductance,
  length,
  luminance,
  magneticFieldIntensity,
  magneticFlux,
  magneticFluxDensity,
  mass,
  time,
  torque,
  waterHardness,
}
