/// Supported conversion types
enum ConversionType {
  area,
  bloodCholesterol,
  capacitance,
  digitalData,
  dynamicViscocity,
  electricCharge,
  electricConductance,
  electricCurrent,
  electricPotential,
  electricResistance,
  force,
  frequency,
  inductance,
  length,
  luminance,
  magneticFieldIntensity,
  magneticFlux,
  magneticFluxDensity,
  mass,
  time,
}
