/// Units of digital data
enum DataUnits {
  bit,
  byte,
  exaBit_Binary,
  exaByte_Binary,
  gigaBit_Binary,
  gigaByte_Binary,
  kiloBit_Binary,
  kiloByte_Binary,
  megaBit_Binary,
  megaByte_Binary,
  petaBit_Binary,
  petaByte_Binary,
  teraBit_Binary,
  teraByte_Binary,
  yottaBit_Binary,
  yottaByte_Binary,
  zettaBit_Binary,
  zettaByte_Binary,
}
