/// Units of magnetic field intensity
enum MagneticFieldIntensityUnits {
  amperePerMeter,
  attoAmperePerMeter,
  centiAmperePerMeter,
  decaAmperePerMeter,
  deciAmperePerMeter,
  exaAmperePerMeter,
  femtoAmperePerMeter,
  gigaAmperePerMeter,
  hectoAmperePerMeter,
  kiloAmperePerMeter,
  megaAmperePerMeter,
  microAmperePerMeter,
  milliAmperePerMeter,
  nanoAmperePerMeter,
  oersted,
  petaAmperePerMeter,
  picoAmperePerMeter,
  teraAmperePerMeter,
  yoctoAmperePerMeter,
  yottaAmperePerMeter,
  zeptoAmperePerMeter,
  zettaAmperePerMeter,
}
