import '../../enum/conversion_type.dart';

// The conversion factor to base unit of each [ConversionType].
final Map<ConversionType, Map<dynamic, double>> conversionFactors = {
  ConversionType.acceleration: <dynamic, double>{},
  ConversionType.area: <dynamic, double>{},
  ConversionType.bloodCholesterol: <dynamic, double>{},
  ConversionType.bloodGlucose: <dynamic, double>{},
  ConversionType.capacitance: <dynamic, double>{},
  ConversionType.data: <dynamic, double>{},
  ConversionType.dataRate: <dynamic, double>{},
  ConversionType.density: <dynamic, double>{},
  ConversionType.dynamicViscocity: <dynamic, double>{},
  ConversionType.electricCharge: <dynamic, double>{},
  ConversionType.electricCurrent: <dynamic, double>{},
  ConversionType.electricPotential: <dynamic, double>{},
  ConversionType.electricalConductance: <dynamic, double>{},
  ConversionType.electricalResistance: <dynamic, double>{},
  ConversionType.energy: <dynamic, double>{},
  ConversionType.force: <dynamic, double>{},
  ConversionType.frequency: <dynamic, double>{},
  ConversionType.illuminance: <dynamic, double>{},
  ConversionType.inductance: <dynamic, double>{},
  ConversionType.kinematicViscocity: <dynamic, double>{},
  ConversionType.length: <dynamic, double>{},
  ConversionType.luminance: <dynamic, double>{},
  ConversionType.magneticFieldIntensity: <dynamic, double>{},
  ConversionType.magneticFlux: <dynamic, double>{},
  ConversionType.magneticFluxDensity: <dynamic, double>{},
  ConversionType.mass: <dynamic, double>{},
  ConversionType.massFlow: <dynamic, double>{},
  ConversionType.massFraction: <dynamic, double>{},
  ConversionType.massMomentOfInertia: <dynamic, double>{},
  ConversionType.massPerArea: <dynamic, double>{},
  ConversionType.moleFraction: <dynamic, double>{},
  ConversionType.planeAngle: <dynamic, double>{},
  ConversionType.power: <dynamic, double>{},
  ConversionType.pressure: <dynamic, double>{},
  ConversionType.radioactivity: <dynamic, double>{},
  ConversionType.speed: <dynamic, double>{},
  ConversionType.time: <dynamic, double>{},
  ConversionType.torque: <dynamic, double>{},
  ConversionType.volume: <dynamic, double>{},
  ConversionType.volumeFlow: <dynamic, double>{},
  ConversionType.volumeFlowPerArea: <dynamic, double>{},
  ConversionType.volumePerArea: <dynamic, double>{},
  ConversionType.waterHardness: <dynamic, double>{},
};
