import '../../enum/prefix.dart';

final Map<Prefix, String> prefixName = {
  Prefix.atto: 'atto',
  Prefix.binaryExa: 'exa',
  Prefix.binaryGiga: 'giga',
  Prefix.binaryKilo: 'kilo',
  Prefix.binaryMega: 'mega',
  Prefix.binaryPeta: 'peta',
  Prefix.binaryTera: 'tera',
  Prefix.binaryYotta: 'yotta',
  Prefix.binaryZetta: 'zetta',
  Prefix.centi: 'centi',
  Prefix.deca: 'deca',
  Prefix.deci: 'deci',
  Prefix.exa: 'exa',
  Prefix.femto: 'femto',
  Prefix.giga: 'giga',
  Prefix.hecto: 'hecto',
  Prefix.kilo: 'kilo',
  Prefix.mega: 'mega',
  Prefix.micro: 'micro',
  Prefix.milli: 'milli',
  Prefix.nano: 'nano',
  Prefix.peta: 'peta',
  Prefix.pico: 'pico',
  Prefix.tera: 'tera',
  Prefix.yocto: 'yocto',
  Prefix.yotta: 'yotta',
  Prefix.zepto: 'zepto',
  Prefix.zetta: 'zetta',
};
