import 'dart:math' show pow;

import '../../enum/length_units.dart';
import '../../enum/prefix.dart';
import '../others/prefix_value.dart';

const _inchToMetre = 0.0254;
final _lightYearToMetre = 9.4607304725808 * prefixValue[Prefix.peta];
final _parsecToMetre = 3.08567782 * pow(10, 16);
const _rodToMetre = 5.0292;

Map<LengthUnits, double> lengthConversionDetails = {
  // Base unit
  LengthUnits.metre: 1,
  LengthUnits.angstrom: prefixValue[Prefix.angstrom],
  LengthUnits.astronomicalUnit: 149597870700,
  LengthUnits.attoLightYear: prefixValue[Prefix.atto] * _lightYearToMetre,
  LengthUnits.attoMetre: prefixValue[Prefix.atto],
  LengthUnits.attoParsec: prefixValue[Prefix.atto] * _parsecToMetre,
  LengthUnits.barleycorn: 0.00846667,
  LengthUnits.centiLightYear: prefixValue[Prefix.centi] * _lightYearToMetre,
  LengthUnits.centiMetre: prefixValue[Prefix.centi],
  LengthUnits.centiParsec: prefixValue[Prefix.centi] * _parsecToMetre,
  LengthUnits.chain: 20.1168,
  LengthUnits.chineseMile: 500,
  LengthUnits.decaLightYear: prefixValue[Prefix.deca] * _lightYearToMetre,
  LengthUnits.decaMetre: prefixValue[Prefix.deca],
  LengthUnits.decaParsec: prefixValue[Prefix.deca] * _parsecToMetre,
  LengthUnits.deciLightYear: prefixValue[Prefix.deci] * _lightYearToMetre,
  LengthUnits.deciMetre: prefixValue[Prefix.deci],
  LengthUnits.deciParsec: prefixValue[Prefix.deci] * _parsecToMetre,
  LengthUnits.exaLightYear: prefixValue[Prefix.exa] * _lightYearToMetre,
  LengthUnits.exaMetre: prefixValue[Prefix.exa],
  LengthUnits.exaParsec: prefixValue[Prefix.exa] * _parsecToMetre,
  LengthUnits.fathom: 1.8288,
  LengthUnits.femtoLightYear: prefixValue[Prefix.femto] * _lightYearToMetre,
  LengthUnits.femtoMetre: prefixValue[Prefix.femto],
  LengthUnits.femtoParsec: prefixValue[Prefix.femto] * _parsecToMetre,
  LengthUnits.fermi: prefixValue[Prefix.femto],
  LengthUnits.foot: 0.3048,
  LengthUnits.foot_USSurvey: 0.304800609601,
  LengthUnits.furlong: 201.168,
  LengthUnits.gigaLightYear: prefixValue[Prefix.giga] * _lightYearToMetre,
  LengthUnits.gigaMetre: prefixValue[Prefix.giga],
  LengthUnits.gigaParsec: prefixValue[Prefix.giga] * _parsecToMetre,
  LengthUnits.hand: 0.1016,
  LengthUnits.hectoLightYear: prefixValue[Prefix.hecto] * _lightYearToMetre,
  LengthUnits.hectoMetre: prefixValue[Prefix.hecto],
  LengthUnits.hectoParsec: prefixValue[Prefix.hecto] * _parsecToMetre,
  LengthUnits.inch: _inchToMetre,
  LengthUnits.kiloLightYear: prefixValue[Prefix.kilo] * _lightYearToMetre,
  LengthUnits.kiloMetre: prefixValue[Prefix.kilo],
  LengthUnits.kiloParsec: prefixValue[Prefix.kilo] * _parsecToMetre,
  LengthUnits.league: 4828.032,
  LengthUnits.lightDay: 2.59020683712 * pow(10, 13),
  LengthUnits.lightHour: 1.0792528488 * prefixValue[Prefix.tera],
  LengthUnits.lightMinute: 1.798754748 * pow(10, 10),
  LengthUnits.lightSecond: 299792458,
  LengthUnits.lightYear: _lightYearToMetre,
  LengthUnits.link: 0.201168,
  LengthUnits.megaLightYear: prefixValue[Prefix.mega] * _lightYearToMetre,
  LengthUnits.megaMetre: prefixValue[Prefix.mega],
  LengthUnits.megaParsec: prefixValue[Prefix.mega] * _parsecToMetre,
  LengthUnits.microInch: prefixValue[Prefix.micro] * _inchToMetre,
  LengthUnits.microLightYear: prefixValue[Prefix.micro] * _lightYearToMetre,
  LengthUnits.microMetre: prefixValue[Prefix.micro],
  LengthUnits.microParsec: prefixValue[Prefix.micro] * _parsecToMetre,
  LengthUnits.micron: prefixValue[Prefix.micro],
  LengthUnits.mile: 1609.344,
  LengthUnits.milliLightYear: prefixValue[Prefix.milli] * _lightYearToMetre,
  LengthUnits.milliMetre: prefixValue[Prefix.milli],
  LengthUnits.milliParsec: prefixValue[Prefix.milli] * _parsecToMetre,
  LengthUnits.nanoLightYear: prefixValue[Prefix.nano] * _lightYearToMetre,
  LengthUnits.nanoMetre: prefixValue[Prefix.nano],
  LengthUnits.nanoParsec: prefixValue[Prefix.nano] * _parsecToMetre,
  LengthUnits.nauticalMile: 1852,
  LengthUnits.parsec: _parsecToMetre,
  LengthUnits.petaLightYear: prefixValue[Prefix.peta] * _lightYearToMetre,
  LengthUnits.petaMetre: prefixValue[Prefix.peta],
  LengthUnits.petaParsec: prefixValue[Prefix.peta] * _parsecToMetre,
  LengthUnits.pica: 0.0042333,
  LengthUnits.picoLightYear: prefixValue[Prefix.pico] * _lightYearToMetre,
  LengthUnits.picoMetre: prefixValue[Prefix.pico],
  LengthUnits.picoParsec: prefixValue[Prefix.pico] * _parsecToMetre,
  LengthUnits.planckLength: 1.616255 * pow(10, -35),
  LengthUnits.point: 0.000352778,
  LengthUnits.pole: _rodToMetre,
  LengthUnits.rod: _rodToMetre,
  LengthUnits.teraLightYear: prefixValue[Prefix.tera] * _lightYearToMetre,
  LengthUnits.teraMetre: prefixValue[Prefix.tera],
  LengthUnits.teraParsec: prefixValue[Prefix.tera] * _parsecToMetre,
  LengthUnits.thousandOfAnInch: 2.54 * pow(10, -5),
  LengthUnits.yard: 0.9144,
  LengthUnits.yoctoLightYear: prefixValue[Prefix.yocto] * _lightYearToMetre,
  LengthUnits.yoctoMetre: prefixValue[Prefix.yocto],
  LengthUnits.yoctoParsec: prefixValue[Prefix.yocto] * _parsecToMetre,
  LengthUnits.yottaLightYear: prefixValue[Prefix.yotta] * _lightYearToMetre,
  LengthUnits.yottaMetre: prefixValue[Prefix.yotta],
  LengthUnits.yottaParsec: prefixValue[Prefix.yotta] * _parsecToMetre,
  LengthUnits.zeptoLightYear: prefixValue[Prefix.zepto] * _lightYearToMetre,
  LengthUnits.zeptoMetre: prefixValue[Prefix.zepto],
  LengthUnits.zeptopPrsec: prefixValue[Prefix.zepto] * _parsecToMetre,
  LengthUnits.zettaLightYear: prefixValue[Prefix.zetta] * _lightYearToMetre,
  LengthUnits.zettaMetre: prefixValue[Prefix.zetta],
  LengthUnits.zettaParsec: prefixValue[Prefix.zetta] * _parsecToMetre,
};
