import 'dart:math' show pow;

import '../../enum/length_units.dart';
import '../../enum/prefix.dart';
import '../others/prefix_value.dart';

const _inchToMeter = .0254;
final _lightYearToMeter = 9.4607304725808 * prefixValue[Prefix.peta];
final _parsecToMeter = 3.08567782 * pow(10, 16);
const _rodToMeter = 5.0292;

Map<LengthUnits, double> lengthConversionDetails = {
  // Base unit
  LengthUnits.meter: 1,
  LengthUnits.angstrom: prefixValue[Prefix.angstrom],
  LengthUnits.astronomicalUnit: 149597870700,
  LengthUnits.attoLightYear: prefixValue[Prefix.atto] * _lightYearToMeter,
  LengthUnits.attoMeter: prefixValue[Prefix.atto],
  LengthUnits.attoParsec: prefixValue[Prefix.atto] * _parsecToMeter,
  LengthUnits.barleycorn: 0.00846667,
  LengthUnits.centiLightYear: prefixValue[Prefix.centi] * _lightYearToMeter,
  LengthUnits.centiMeter: prefixValue[Prefix.centi],
  LengthUnits.centiParsec: prefixValue[Prefix.centi] * _parsecToMeter,
  LengthUnits.chain: 20.1168,
  LengthUnits.chineseMile: 500,
  LengthUnits.decaLightYear: prefixValue[Prefix.deca] * _lightYearToMeter,
  LengthUnits.decaMeter: prefixValue[Prefix.deca],
  LengthUnits.decaParsec: prefixValue[Prefix.deca] * _parsecToMeter,
  LengthUnits.deciLightYear: prefixValue[Prefix.deci] * _lightYearToMeter,
  LengthUnits.deciMeter: prefixValue[Prefix.deci],
  LengthUnits.deciParsec: prefixValue[Prefix.deci] * _parsecToMeter,
  LengthUnits.exaLightYear: prefixValue[Prefix.exa] * _lightYearToMeter,
  LengthUnits.exaMeter: prefixValue[Prefix.exa],
  LengthUnits.exaParsec: prefixValue[Prefix.exa] * _parsecToMeter,
  LengthUnits.fathom: 1.8288,
  LengthUnits.femtoLightYear: prefixValue[Prefix.femto] * _lightYearToMeter,
  LengthUnits.femtoMeter: prefixValue[Prefix.femto],
  LengthUnits.femtoParsec: prefixValue[Prefix.femto] * _parsecToMeter,
  LengthUnits.fermi: prefixValue[Prefix.femto],
  LengthUnits.foot: .3048,
  LengthUnits.furlong: 201.168,
  LengthUnits.gigaLightYear: prefixValue[Prefix.giga] * _lightYearToMeter,
  LengthUnits.gigaMeter: prefixValue[Prefix.giga],
  LengthUnits.gigaParsec: prefixValue[Prefix.giga] * _parsecToMeter,
  LengthUnits.hand: .1016,
  LengthUnits.hectoLightYear: prefixValue[Prefix.hecto] * _lightYearToMeter,
  LengthUnits.hectoMeter: prefixValue[Prefix.hecto],
  LengthUnits.hectoParsec: prefixValue[Prefix.hecto] * _parsecToMeter,
  LengthUnits.inch: _inchToMeter,
  LengthUnits.kiloLightYear: prefixValue[Prefix.kilo] * _lightYearToMeter,
  LengthUnits.kiloMeter: prefixValue[Prefix.kilo],
  LengthUnits.kiloParsec: prefixValue[Prefix.kilo] * _parsecToMeter,
  LengthUnits.league: 4828.032,
  LengthUnits.lightDay: 2.59020683712 * pow(10, 13),
  LengthUnits.lightHour: 1.0792528488 * prefixValue[Prefix.tera],
  LengthUnits.lightMinute: 1.798754748 * pow(10, 10),
  LengthUnits.lightSecond: 299792458,
  LengthUnits.lightYear: _lightYearToMeter,
  LengthUnits.link: .201168,
  LengthUnits.megaLightYear: prefixValue[Prefix.mega] * _lightYearToMeter,
  LengthUnits.megaMeter: prefixValue[Prefix.mega],
  LengthUnits.megaParsec: prefixValue[Prefix.mega] * _parsecToMeter,
  LengthUnits.microInch: prefixValue[Prefix.micro] * _inchToMeter,
  LengthUnits.microLightYear: prefixValue[Prefix.micro] * _lightYearToMeter,
  LengthUnits.microMeter: prefixValue[Prefix.micro],
  LengthUnits.microParsec: prefixValue[Prefix.micro] * _parsecToMeter,
  LengthUnits.micron: prefixValue[Prefix.micro],
  LengthUnits.mile: 1609.344,
  LengthUnits.milliLightYear: prefixValue[Prefix.milli] * _lightYearToMeter,
  LengthUnits.milliMeter: prefixValue[Prefix.milli],
  LengthUnits.milliParsec: prefixValue[Prefix.milli] * _parsecToMeter,
  LengthUnits.nanoLightYear: prefixValue[Prefix.nano] * _lightYearToMeter,
  LengthUnits.nanoMeter: prefixValue[Prefix.nano],
  LengthUnits.nanoParsec: prefixValue[Prefix.nano] * _parsecToMeter,
  LengthUnits.nauticalMile: 1852,
  LengthUnits.parsec: _parsecToMeter,
  LengthUnits.petaLightYear: prefixValue[Prefix.peta] * _lightYearToMeter,
  LengthUnits.petaMeter: prefixValue[Prefix.peta],
  LengthUnits.petaParsec: prefixValue[Prefix.peta] * _parsecToMeter,
  LengthUnits.pica: .0042333,
  LengthUnits.picoLightYear: prefixValue[Prefix.pico] * _lightYearToMeter,
  LengthUnits.picoMeter: prefixValue[Prefix.pico],
  LengthUnits.picoParsec: prefixValue[Prefix.pico] * _parsecToMeter,
  LengthUnits.planckLength: 1.616255 * pow(10, -35),
  LengthUnits.point: 0.000352778,
  LengthUnits.pole: _rodToMeter,
  LengthUnits.rod: _rodToMeter,
  LengthUnits.teraLightYear: prefixValue[Prefix.tera] * _lightYearToMeter,
  LengthUnits.teraMeter: prefixValue[Prefix.tera],
  LengthUnits.teraParsec: prefixValue[Prefix.tera] * _parsecToMeter,
  LengthUnits.thousandOfAnInch: 2.54 * pow(10, -5),
  LengthUnits.yard: .9144,
  LengthUnits.yoctoLightYear: prefixValue[Prefix.yocto] * _lightYearToMeter,
  LengthUnits.yoctoMeter: prefixValue[Prefix.yocto],
  LengthUnits.yoctoParsec: prefixValue[Prefix.yocto] * _parsecToMeter,
  LengthUnits.yottaLightYear: prefixValue[Prefix.yotta] * _lightYearToMeter,
  LengthUnits.yottaMeter: prefixValue[Prefix.yotta],
  LengthUnits.yottaParsec: prefixValue[Prefix.yotta] * _parsecToMeter,
  LengthUnits.zeptoLightYear: prefixValue[Prefix.zepto] * _lightYearToMeter,
  LengthUnits.zeptoMeter: prefixValue[Prefix.zepto],
  LengthUnits.zeptopPrsec: prefixValue[Prefix.zepto] * _parsecToMeter,
  LengthUnits.zettaLightYear: prefixValue[Prefix.zetta] * _lightYearToMeter,
  LengthUnits.zettaMeter: prefixValue[Prefix.zetta],
  LengthUnits.zettaParsec: prefixValue[Prefix.zetta] * _parsecToMeter,
};
