import 'package:unit_converter/src/constant/misc_constants.dart';
import 'package:unit_converter/src/enum/length_units.dart';
import 'package:unit_converter/src/misc/global.dart';
import 'package:unit_converter/src/model/unit.dart';

Set<Unit> lengthUnitDetails = {
  Unit('Femtometer', 'fm', LengthUnits.femtometer),
  Unit('Picometer', 'pm', LengthUnits.picometer),
  Unit('Angstrom', createStringFromUnicode(unicodeAngstrom),
      LengthUnits.angstrom),
  Unit('Nanometer', 'nm', LengthUnits.nanometer),
  Unit('Micrometer', createStringFromUnicode(unicodeMicro, postfix: 'm'),
      LengthUnits.micrometer),
  Unit('Millimeter', 'mm', LengthUnits.millimeter),
  Unit('Centimeter', 'cm', LengthUnits.centimeter),
  Unit('Decimeter', 'dm', LengthUnits.decimeter),
  Unit('Meter', 'm', LengthUnits.meter),
  Unit('Decameter', 'dam', LengthUnits.decameter),
  Unit('Hectometer', 'hm', LengthUnits.hectometer),
  Unit('Kilometer', 'km', LengthUnits.kilometer),
  Unit('Megameter', 'Mm', LengthUnits.megameter),
  Unit('Gigameter', 'Gm', LengthUnits.gigameter),
  Unit('Tetrameter', 'Tm', LengthUnits.terameter),
  Unit('Inch', 'in', LengthUnits.inch),
  Unit('Foot', 'ft', LengthUnits.foot),
  Unit('Yard', 'yd', LengthUnits.yard),
  Unit('Mile', 'mi', LengthUnits.mile),
  Unit('Nautical Mile', 'nmi', LengthUnits.nauticalMile),
  Unit('Rod', 'rod', LengthUnits.rod),
  Unit('Astronomical Unit', 'au', LengthUnits.astronomicalUnit),
  Unit('Furlong', 'fur', LengthUnits.furlong),
  Unit('Chain', 'chain', LengthUnits.chain),
  Unit('Point', 'pt', LengthUnits.point),
  Unit('Light Year', 'ly', LengthUnits.lightYear),
  Unit('Light Second', 'light-second', LengthUnits.lightSecond),
  Unit('Fathom', 'ftm', LengthUnits.fathom),
  Unit('Parsec', 'pc', LengthUnits.parsec),
  Unit('Megaparsec', 'Mpc', LengthUnits.megaparsec),
  Unit('Barleycorn', 'bc', LengthUnits.barleycorn),
  Unit('Pica', 'pica', LengthUnits.pica),
  Unit('Planck Length', createStringFromUnicode('2133', postfix: 'p'),
      LengthUnits.planckLength),
  Unit('Chinese Mile', 'li', LengthUnits.chineseMile),
};
