import 'dart:math';

import '../../enum/length_units.dart';
import '../../enum/prefix.dart';
import '../others/prefix_value.dart';

final _inchToMeter = .0254;
final _lightYearToMeter = 9.4607304725808 * prefixValue[Prefix.peta];
final _parsecToMeter = 3.08567782 * pow(10, 16);
final _rodToMeter = 5.0292;

Map<LengthUnits, double> lengthConversionDetails = {
  // Base unit
  LengthUnits.meter: 1,
  LengthUnits.angstrom: prefixValue[Prefix.angstrom],
  LengthUnits.astronomicalUnit: 149597870700,
  LengthUnits.attoLightYear: prefixValue[Prefix.atto] * _lightYearToMeter,
  LengthUnits.attometer: prefixValue[Prefix.atto],
  LengthUnits.attoparsec: prefixValue[Prefix.atto] * _parsecToMeter,
  LengthUnits.barleycorn: 0.00846667,
  LengthUnits.centiLightYear: prefixValue[Prefix.centi] * _lightYearToMeter,
  LengthUnits.centimeter: prefixValue[Prefix.centi],
  LengthUnits.centiparsec: prefixValue[Prefix.centi] * _parsecToMeter,
  LengthUnits.chain: 20.1168,
  LengthUnits.chineseMile: 500,
  LengthUnits.decaLightYear: prefixValue[Prefix.deca] * _lightYearToMeter,
  LengthUnits.decameter: prefixValue[Prefix.deca],
  LengthUnits.decaparsec: prefixValue[Prefix.deca] * _parsecToMeter,
  LengthUnits.deciLightYear: prefixValue[Prefix.deci] * _lightYearToMeter,
  LengthUnits.decimeter: prefixValue[Prefix.deci],
  LengthUnits.deciparsec: prefixValue[Prefix.deci] * _parsecToMeter,
  LengthUnits.exaLightYear: prefixValue[Prefix.exa] * _lightYearToMeter,
  LengthUnits.exameter: prefixValue[Prefix.exa],
  LengthUnits.exaparsec: prefixValue[Prefix.exa] * _parsecToMeter,
  LengthUnits.fathom: 1.8288,
  LengthUnits.femtoLightYear: prefixValue[Prefix.femto] * _lightYearToMeter,
  LengthUnits.femtometer: prefixValue[Prefix.femto],
  LengthUnits.femtoparsec: prefixValue[Prefix.femto] * _parsecToMeter,
  LengthUnits.fermi: prefixValue[Prefix.femto],
  LengthUnits.foot: .3048,
  LengthUnits.furlong: 201.168,
  LengthUnits.gigaLightYear: prefixValue[Prefix.giga] * _lightYearToMeter,
  LengthUnits.gigameter: prefixValue[Prefix.giga],
  LengthUnits.gigaparsec: prefixValue[Prefix.giga] * _parsecToMeter,
  LengthUnits.hand: .1016,
  LengthUnits.hectoLightYear: prefixValue[Prefix.hecto] * _lightYearToMeter,
  LengthUnits.hectometer: prefixValue[Prefix.hecto],
  LengthUnits.hectoparsec: prefixValue[Prefix.hecto] * _parsecToMeter,
  LengthUnits.inch: _inchToMeter,
  LengthUnits.kiloLightYear: prefixValue[Prefix.kilo] * _lightYearToMeter,
  LengthUnits.kilometer: prefixValue[Prefix.kilo],
  LengthUnits.kiloparsec: prefixValue[Prefix.kilo] * _parsecToMeter,
  LengthUnits.lightDay: 2.59020683712 * pow(10, 13),
  LengthUnits.lightHour: 1.0792528488 * prefixValue[Prefix.tera],
  LengthUnits.lightMinute: 1.798754748 * pow(10, 10),
  LengthUnits.lightSecond: 299792458,
  LengthUnits.lightYear: _lightYearToMeter,
  LengthUnits.megaLightYear: prefixValue[Prefix.mega] * _lightYearToMeter,
  LengthUnits.megameter: prefixValue[Prefix.mega],
  LengthUnits.megaparsec: prefixValue[Prefix.mega] * _parsecToMeter,
  LengthUnits.microLightYear: prefixValue[Prefix.micro] * _lightYearToMeter,
  LengthUnits.microinch: prefixValue[Prefix.micro] * _inchToMeter,
  LengthUnits.micrometer: prefixValue[Prefix.micro],
  LengthUnits.micron: prefixValue[Prefix.micro],
  LengthUnits.microparsec: prefixValue[Prefix.micro] * _parsecToMeter,
  LengthUnits.mile: 1609.344,
  LengthUnits.milliLightYear: prefixValue[Prefix.milli] * _lightYearToMeter,
  LengthUnits.millimeter: prefixValue[Prefix.milli],
  LengthUnits.milliparsec: prefixValue[Prefix.milli] * _parsecToMeter,
  LengthUnits.nanoLightYear: prefixValue[Prefix.nano] * _lightYearToMeter,
  LengthUnits.nanometer: prefixValue[Prefix.nano],
  LengthUnits.nanoparsec: prefixValue[Prefix.nano] * _parsecToMeter,
  LengthUnits.nauticalMile: 1852,
  LengthUnits.parsec: _parsecToMeter,
  LengthUnits.petaLightYear: prefixValue[Prefix.peta] * _lightYearToMeter,
  LengthUnits.petameter: prefixValue[Prefix.peta],
  LengthUnits.petaparsec: prefixValue[Prefix.peta] * _parsecToMeter,
  LengthUnits.pica: .0042333,
  LengthUnits.picoLightYear: prefixValue[Prefix.pico] * _lightYearToMeter,
  LengthUnits.picometer: prefixValue[Prefix.pico],
  LengthUnits.picoparsec: prefixValue[Prefix.pico] * _parsecToMeter,
  LengthUnits.planckLength: 1.616255 * pow(10, -35),
  LengthUnits.point: 0.000352778,
  LengthUnits.pole: _rodToMeter,
  LengthUnits.rod: _rodToMeter,
  LengthUnits.teraLightYear: prefixValue[Prefix.tera] * _lightYearToMeter,
  LengthUnits.terameter: prefixValue[Prefix.tera],
  LengthUnits.teraparsec: prefixValue[Prefix.tera] * _parsecToMeter,
  LengthUnits.thousandOfAnInch: 2.54 * pow(10, -5),
  LengthUnits.yard: .9144,
  LengthUnits.yoctoLightYear: prefixValue[Prefix.yocto] * _lightYearToMeter,
  LengthUnits.yoctometer: prefixValue[Prefix.yocto],
  LengthUnits.yoctoparsec: prefixValue[Prefix.yocto] * _parsecToMeter,
  LengthUnits.yottaLightYear: prefixValue[Prefix.yotta] * _lightYearToMeter,
  LengthUnits.yottameter: prefixValue[Prefix.yotta],
  LengthUnits.yottaparsec: prefixValue[Prefix.yotta] * _parsecToMeter,
  LengthUnits.zeptoLightYear: prefixValue[Prefix.zepto] * _lightYearToMeter,
  LengthUnits.zeptometer: prefixValue[Prefix.zepto],
  LengthUnits.zeptoparsec: prefixValue[Prefix.zepto] * _parsecToMeter,
  LengthUnits.zettaLightYear: prefixValue[Prefix.zetta] * _lightYearToMeter,
  LengthUnits.zettameter: prefixValue[Prefix.zetta],
  LengthUnits.zettaparsec: prefixValue[Prefix.zetta] * _parsecToMeter,
};
